default:
    image: python:3.13

variables:
  PIP_CACHE_DIR: $CI_PROJECT_DIR/.cache/pip

include:
  - project: 'wjs/wjs-profile-project'
    ref: 'wjs-develop'
    file: '.gitlab-ci-pre-commit.yml'

pre-commit:
  extends:
    - .run-pre-commit

run-tests:
  stage: test
  tags:
    - fast-test
  script:
    - pip install --cache $PIP_CACHE_DIR --user .[test]
    - python -m pytest
