default:
  image: python:3.13
  cache:
    key: cache-default
    paths:
      - .cache

variables:
  PIP_CACHE_DIR: $CI_PROJECT_DIR/.cache/pip

include:
  - project: 'wjs/wjs-profile-project'
    ref: 'wjs-develop'
    file: '.gitlab-ci-pre-commit.yml'

pre-commit:
  stage: test
  tags:
    - fast-test

  variables:
    # Use the following after force-pushes:
    # GIT_STRATEGY: clone
    PRE_COMMIT_HOME: .pre-commit

  script:
    - pip install --cache $PIP_CACHE_DIR --user pre-commit
    - python -m pre_commit run -a

#- .run-pre-commit

run-tests:
  stage: test
  tags:
    - fast-test
  script:
    - pip install --cache $PIP_CACHE_DIR --user .[test]
    - python -m pytest
